### ISSUE TITLE
Does multilingual-t5 need tensor2tensor ?

### ISSUE THREAD

**Issue by hisashi-ito** [google-research/multilingual-t5#82]
Hi.
About half a year ago, when I fine-tuned the original japanise summarization task with multilingual-t5, it worked fine.
But, Same task does not work. :_(

library version and error is as follows.

* library
```
t5[gcp]==0.7.1
tensorflow-gpu==2.3.0
mesh-tensorflow==0.1.17
tensorflow-datasets==4.1.0
tensorflow-text==2.3.0
```
* error
```
INFO:tensorflow:training_loop marked as finished
I0507 05:11:07.176133 140511804491584 error_handling.py:115] training_loop marked as finished
WARNING:tensorflow:Reraising captured error
W0507 05:11:07.176389 140511804491584 error_handling.py:149] Reraising captured error
Traceback (most recent call last):
  File "/usr/local/bin/t5_mesh_transformer", line 8, in <module>
    sys.exit(console_entry_point())
  File "/usr/local/lib/python3.6/dist-packages/t5/models/mesh_transformer_main.py", line 262, in console_entry_point
    app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/usr/local/lib/python3.6/dist-packages/t5/models/mesh_transformer_main.py", line 256, in main
    model_dir=FLAGS.model_dir)
  File "/usr/local/lib/python3.6/dist-packages/gin/config.py", line 1069, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/usr/local/lib/python3.6/dist-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/usr/local/lib/python3.6/dist-packages/gin/config.py", line 1046, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mesh_tensorflow/transformer/utils.py", line 2302, in run
    skip_seen_data=skip_seen_data)
  File "/usr/local/lib/python3.6/dist-packages/mesh_tensorflow/transformer/utils.py", line 1615, in train_model
    estimator.train(input_fn=input_fn, max_steps=train_steps)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3089, in train
    rendezvous.raise_errors()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/error_handling.py", line 150, in raise_errors
    six.reraise(typ, value, traceback)
  File "/usr/local/lib/python3.6/dist-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3084, in train
    saving_listeners=saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 349, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1175, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1201, in _train_model_default
    self._get_features_and_labels_from_input_fn(input_fn, ModeKeys.TRAIN))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1037, in _get_features_and_labels_from_input_fn
    self._call_input_fn(input_fn, mode))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3041, in _call_input_fn
    return input_fn(**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mesh_tensorflow/transformer/utils.py", line 1602, in input_fn
    dataset_split=dataset_split)
  File "/usr/local/lib/python3.6/dist-packages/gin/config.py", line 1069, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/usr/local/lib/python3.6/dist-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/usr/local/lib/python3.6/dist-packages/gin/config.py", line 1046, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/t5/models/mesh_transformer.py", line 73, in mesh_train_dataset_fn
    feature_keys=feature_keys, ensure_eos=eos_keys)
  File "/usr/local/lib/python3.6/dist-packages/gin/config.py", line 1069, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/usr/local/lib/python3.6/dist-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/usr/local/lib/python3.6/dist-packages/gin/config.py", line 1046, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mesh_tensorflow/transformer/dataset.py", line 123, in pack_or_pad
    dataset = pack_dataset(dataset, length=length, keys=feature_keys)
  File "/usr/local/lib/python3.6/dist-packages/gin/config.py", line 1069, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/usr/local/lib/python3.6/dist-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/usr/local/lib/python3.6/dist-packages/gin/config.py", line 1046, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mesh_tensorflow/transformer/dataset.py", line 551, in pack_dataset
    dataset = _pack_with_custom_ops(dataset, keys, length)
  File "/usr/local/lib/python3.6/dist-packages/mesh_tensorflow/transformer/dataset.py", line 690, in _pack_with_custom_ops
    from tensor2tensor.data_generators.ops import pack_sequences_ops  # pylint: disable=g-import-not-at-top
ModuleNotFoundError: No module named 'tensor2tensor'
  In call to configurable 'pack_dataset' (<function pack_dataset at 0x7fcafcd94e18>)
  In call to configurable 'pack_or_pad' (<function pack_or_pad at 0x7fcafcd85bf8>)
  In call to configurable 'mesh_train_dataset_fn' (<function mesh_train_dataset_fn at 0x7fcafd0e6840>)
  In call to configurable 'run' (<function run at 0x7fcafccc5b70>)
```
* My qestion
Does multilingual-t5 need tensor2tensor ? About half a year ago,  I don't know this error.
Then, installed `tensor2tensor==1.15.7` . but error occoerd. 

```text
  File "/usr/local/lib/python3.6/dist-packages/mesh_tensorflow/transformer/dataset.py", line 690, in _pack_with_custom_ops
    from tensor2tensor.data_generators.ops import pack_sequences_ops  # pylint: disable=g-import-not-at-top
```
Pelase tell me about advice.

**Comment by adarob** [comment]
You shouldn't as long as use_custom_ops is set to False.

**Comment by hisashi-ito** [comment]
hi, @adarob 

> You shouldn't as long as use_custom_ops is set to False.

* pretrained_models_mt5_small_pretrain_operative_config.gin
```
# pack_dataset.use_custom_ops = True
pack_dataset.use_custom_ops = False
```
It's Works!! 😆
Thank you. I'm sorry to trouble you.
